spring:
  application:
    name: guestbook
  profiles: local-dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guestdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&connectionCollation=utf8_general_ci
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        generate_statistics: false
    database: MYSQL
    show-sql: true
    generate-ddl: true
  message:
    basename: validation
  servlet:
    multipart: 
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 8099
  max-http-header-size: 64KB
  
logging:
  config: classpath:logback-spring.xml
